name: "Terraform CI (Lint, Validate & Security)"

on:
  push:
    branches: [main, develop, feat/ci-cd]
    paths:
      - "environments/**"
      - "modules/**"
      - "*.tf"
      - ".github/workflows/terraform-*.yml"
  pull_request:
    branches: [main, develop, feat/ci-cd]
    paths:
      - "environments/**"
      - "modules/**"
      - "*.tf"
      - ".github/workflows/terraform-*.yml"

jobs:
  validate:
    name: "Validar Terraform (Dev & Prod)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositorio Infraestrutura
        uses: actions/checkout@v4

      - name: Checkout do Modulo Lambda-Alexa
        uses: actions/checkout@v4
        with:
          repository: 'LuminaPI52CCOA/Lambda-Alexa'
          ref: 'main'
          path: 'Lambda-Alexa'

      - name: Checkout do Modulo Data-Pipeline
        uses: actions/checkout@v4
        with:
          repository: 'LuminaPI52CCOA/Data-Pipeline'
          ref: 'main'
          path: 'Data-Pipeline'

      - name: Configurar estrutura de pastas multi-repo
        run: |
          mkdir -p ../../../Lambda-Alexa
          cp -r Lambda-Alexa/* ../../../Lambda-Alexa/ 2>/dev/null || true
          mkdir -p ../../Lambda-Alexa
          cp -r Lambda-Alexa/* ../../Lambda-Alexa/ 2>/dev/null || true
          mkdir -p ../Lambda-Alexa
          cp -r Lambda-Alexa/* ../Lambda-Alexa/ 2>/dev/null || true
          mkdir -p ../../../Data-Pipeline
          cp -r Data-Pipeline/* ../../../Data-Pipeline/ 2>/dev/null || true
          mkdir -p ../../Data-Pipeline
          cp -r Data-Pipeline/* ../../Data-Pipeline/ 2>/dev/null || true
          mkdir -p ../Data-Pipeline
          cp -r Data-Pipeline/* ../Data-Pipeline/ 2>/dev/null || true

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"

      - name: Verificar Formatacao (terraform fmt)
        run: terraform fmt -check -recursive

      - name: Validar Ambiente Dev
        working-directory: ./environments/dev
        run: |
          terraform init -backend=false
          terraform validate

      - name: Validar Ambiente Prod
        working-directory: ./environments/prod
        run: |
          terraform init -backend=false
          terraform validate

      - name: Validar Ambiente Data
        working-directory: ./environments/data
        run: |
          terraform init -backend=false
          terraform validate
